controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
kernel:
    resource: ../src/Kernel.php
    type: attribute

api_login_check:
    path: /api/login_check

 # config/routes.yaml
suppliers_list:
    path: /api/suppliers
    controller: App\Controller\SupplierController::index
    methods: GET

products_list:
    path: /api/products
    controller: App\Controller\ProductController::index
    methods: GET

# config/routes.yaml
token_refresh:
    path: /api/token/refresh
    controller: App\Controller\AuthController::refreshToken
    methods: [POST]
